config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles do
    resources :articles
    resources :messages
    resources :conversations

  end


  resources :messages do
    resources :messagecommits
  end
  resources :articles do
    resources :articlecommits
  end
  resources :contacts
resources :conversations do
    resources :conversationcommits
  end
  get 'pages/pourquoi'
  get 'pages/info'
  get 'pages/liens'
  get 'pages/admin'
  get 'pages/mention'
  get 'pages/test'
  get 'valider_profile', to: 'profiles#valider_profile'
  get 'refuser_profile', to: 'profiles#refuser_profile'
  get 'valider_article', to: 'articles#valider_article'
  get 'refuser_article', to: 'articles#refuser_article'
  get 'effacer_contact', to: 'contacts#effacer_contact'
  get 'bloquer_profile', to: 'profiles#bloquer_profile'

  get 'rendre_admin', to: 'profiles#rendre_admin'
  get 'rendre_nonadmin', to: 'profiles#rendre_nonadmin'


  get 'supprimer_profile', to: 'profiles#supprimer_profile'
  get 'debloquer_profile', to: 'profiles#debloquer_profile'
  get 'supprimer_conversation', to: 'conversations#supprimer_conversation'
  get 'supprimer_notification', to: 'notifications#supprimer_notification'

  get 'pages/notification'

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :profile
  has_many :messagecommits, dependent: :destroy
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
    @profile = current_user.profile
  end

  def show
    @message = Message.find(params[:id])
    @messages = Message.all
    @profile = Profile.find(@message.profile_id)
  end

  def index
    @messages =Message.all
  end

  def create
    @message = Message.new(message_params)
    @profile = current_user.profile
    @message.profile = @profile
    @message.statut = "yes"

    if @message.save
      flash[:notice] = 'Votre message a été envoyé !'
      redirect_to message_path(@message.id)
    else
      render :new
      flash[:notice] = 'Une erreur est survenue, veuillez recommencer ...'
    end
  end

  private

  def message_params
    params.require(:message).permit(:title, :theme, :content, :statut)
  end
end

app/views/messages/index.html.erb
    <div class="text-left page">
      <!-- Page preloader-->
      <div class="page-loader">
        <div>
          <div class="page-loader-body">
            <svg x="0" y="0" width="258" height="258">

              <clippath id="clip-path">

              </clippath>
            </svg>
          </div>
        </div>
      </div>
      <!-- Page Header-->
      <section class="section section-breadcrumb">
        <div class="parallax-container breadcrumb-wrapper" data-parallax-img="https://images.unsplash.com/photo-1525248152312-434c15a82f37?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=278e9355f4294b036c0ad9d60750e752&auto=format&fit=crop&w=2880&q=80">
          <div class="parallax-content section-lg context-dark">
            <div class="shell context-dark">
              <h2 style="color: black;">Le forum</h2>
              <div class="divider"></div>
            </div>
          </div>
        </div>
      </section>
            <br/>
      <br/>

<div class="container">
<i>Sur cette page de forum, vous verrez la liste des sujets de discussion postés par les inscrits . Pour pouvoir discuter sur un de ceux-ci, cliquez sur le bouton "voir" du sujet voulu, vous pourrez alors voir le contenu complet de celui-ci et commenter à votre guise, n'oubliez pas que c'est en participant que nous avancerons et ferons de ce site une plateforme bénéfique, incontournable et bienveillante . Pour poster un nouveau sujet, veuillez vous rendre en bas de cette page et cliquez sur le bouton "poster un nouveau sujet".</i>
 <div class="divider"></div>
      <section class="section section-lg bg-white">

        <div class="shell bg-white-lighter block-info-wrap">
          <div class="block-info-wrap-inner">

            <% @messages.where(statut: 'yes').each do |message| %>
              <% @profile = Profile.find(message.profile_id)  %>
            <div class="block-info-wrap-item">
              <div class="block-info">
                <div class="block-info-inner">

                      <% if @profile.photo.nil? %>
                        <img class ="img-circle" src="https://res.cloudinary.com/dz83jh064/image/upload/v1517825470/images_z0whi1.png" size="300*300" crop="fill" alt=""/>
                      <% else %>
                        <%= cl_image_tag @profile.photo, class:"img-circle", size:"300x300", crop:"fill", alt:""%>
                      <% end %>



                  <i>Thème : <%=message.theme.capitalize%></i>
                  <H5><%=message.title%></H5>


                  <p class="heading-5">Posté le <%=message.created_at.strftime("%d.%m.%Y") %> par <%= @profile.pseudo.capitalize %></p>
                  <% @comments = Messagecommit.where(message_id: message.id).length%>
                  <i>Nombre de commentaires : <%=@comments%></i>

                <%= link_to 'Voir', profile_message_path(message.profile_id, message.id), class:"button button-effect-ujarak button-primary button-block"%>

                </div>
              </div>
            </div>

            <% end %>


          </div>
        </div>
      </section>
      <!-- Page Footer-->
      <section class="section section-sm bg-white-lighter">
        <div class="shell shell-out">
          <div class="range range-30">
            <div class="cell-sm-3 cell-xs-5">
              <div class="preffix-xl-70" style="max-width: 274px">
                <h6 class="text-spacing-200 text-uppercase font-base">Quelques chiffres</h6>
                <div class="divider-modern"></div>
                <ul class="list list-md">
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"><span class="icon icon-md icon-primary mdi-phone"></span></div>
                      <div class="unit-body"><i class="link-gray-darker" href="tel:#">nb total de messages = <%=@messages.length%></i></div>
                    </div>
                  </li>
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"><span class="icon icon-md icon-primary mdi-email-outline"></span></div>
                      <% @total = Messagecommit.all.length %>

                      <div class="unit-body" style="position: relative; top: 1px"><i class="link-gray-darker" href="mailto:#">nb total de commentaires = <%=@total%> </i></div>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
            <div class="cell-sm-3 cell-xs-5">
              <div class="preffix-xl-70" style="max-width: 274px">
                <h6 class="text-spacing-200 text-uppercase font-base">Dernier sujet posté</h6>

                <div class="divider-modern"></div>
                <ul class="list list-md">
                  <li>
                <% if @messages.length > 0 %>

                <% @lastmessage = @messages.where(statut: 'yes').last(1) %>
                <% @lastprofile = Profile.find(@lastmessage.last.profile_id)  %>
                    <div class="unit unit-spacing-xs unit-horizontal">
                      <div class="unit-left"><span class="icon icon-md-biger icon-primary mdi-map-marker"></span></div>
                      <div class="unit-body" style="position: relative; top: -4px;"><a class="link-default" href="<%=profile_message_path(@lastprofile.id,@lastmessage.last.id) %>"><%= @lastmessage.last.title%> par <%=@lastprofile.pseudo.capitalize %></a></div>
                    </div>
                <% else %>
                <i>Aucun message</i>
                <% end %>
                  </li>
                </ul>
              </div>
            </div>
            <div class="cell-sm-4">
              <div class="preffix-xl-70" style="max-width: 433px">
                <%= link_to 'Accueil', root_path, class:"button button-effect-ujarak button-primary button-block"%>
                <%= link_to 'Poster un nouveau sujet', new_profile_message_path(current_user.profile.id), class:"button button-effect-ujarak button-primary button-block"%>
              </div>
            </div>
          </div>
        </div>
      </section>

    </div>
    <!-- PANEL-->
    <!-- END PANEL-->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>

app/views/messages/new.html.erb
<div class="text-left page">
      <!-- Page preloader-->
      <div class="page-loader">
        <div>
          <div class="page-loader-body">
            <svg x="0" y="0" width="258" height="258">

              <clippath id="clip-path">

              </clippath>
            </svg>
          </div>
        </div>
      </div>
      <!-- Page Header-->

      <section class="section section-breadcrumb">
        <div class="parallax-container breadcrumb-wrapper" data-parallax-img="https://images.unsplash.com/photo-1525450101819-1517c5c00f45?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f37e6d87ac7833c774b03b2c15b05b90&auto=format&fit=crop&w=2850&q=80">
          <div class="parallax-content section-lg context-dark">
            <div class="shell context-dark">
              <h2>Poster un message</h2>
              <div class="divider"></div>
            </div>
          </div>
        </div>

      </section>
      <!-- Get in Touch-->
      <section class="section section-lg bg-white">
        <div class="shell">
          <div class="range range-30">
            <div class="cell-md-5">
              <div class="form-block">
                <h3>Mon message</h3>
                <p>Vous pouvez rédiger votre message ici.
                </p>
                <%= simple_form_for [@profile, @message] do |f| %>

                <form class="rd-mailform" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php">
                  <div class="range range-xs-center range-20 range-narrow">
                    <div class="cell-sm-5">
                      <div class="form-wrap form-wrap-validation">
                         <%= f.input :theme, collection: ["Travail", "Famille", "Mes difficultés", "Mes solutions", "Culture", "Vie associative"], class: "form-control form-control-last-child", label: false, placeholder:"Choisissez votre Thème" %>
                      </div>
                    </div>
                    <div class="cell-sm-5">
                      <div class="form-wrap form-wrap-validation">

                        <%= f.input :title , id:"contacts-last-name", type:"text", name:"Adresse", required: true, class: "form-control form-control-last-child", label: false, placeholder:"Titre du message"%>

                      </div>
                    </div>
                    <div class="cell-sm-10">
                      <div class="form-wrap form-wrap-validation">
                    <%= f.input :content , :as => :text, input_html: {style: 'max-height:1500px;'}, required: true, class: "form-control form-control-last-child", label: false, placeholder:"Écrivez ici" %>

                      </div>
                    </div>



                    <div class="cell-sm-5">
                      <div class="form-button">
                        <button class="button button-effect-ujarak button-primary button-block button-square" type="submit">Poster</button>
                      </div>
                    </div>
                  </div>
                </form>
                <% end %>
              </div>
            </div>
            <div class="cell-md-5 gm-contact-wrap">
              <div class="gm-contact-inner">

               <img class="img-responsive center-block" src="http://res.cloudinary.com/dz83jh064/image/upload/c_scale,w_700/v1527151617/photo-1462642109801-4ac2971a3a51_zjfuf6.jpg" alt=""  />

              </div>
            </div>
          </div>
        </div>
      </section>

    </div>
    <!-- PANEL-->
    <!-- END PANEL-->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->

app/views/messages/show.html.erb
    <div class="text-left page">
      <!-- Page preloader-->
      <div class="page-loader">
        <div>
          <div class="page-loader-body">
            <svg x="0" y="0" width="258" height="258">
              <clippath id="clip-path">

              </clippath>
            </svg>
          </div>
        </div>
      </div>


      <section class="section section-breadcrumb">
        <div class="parallax-container breadcrumb-wrapper" data-parallax-img="https://images.unsplash.com/photo-1525248152312-434c15a82f37?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=278e9355f4294b036c0ad9d60750e752&auto=format&fit=crop&w=2880&q=80">
          <div class="parallax-content section-lg context-dark">
            <div class="shell context-dark">
              <h2 style="color: black;">Message de <%=@profile.pseudo.capitalize%></h2>
              <div class="divider"></div>
            </div>
          </div>
        </div>

      </section>
      <section class="section section-lg bg-white text-left">
        <div class="shell">
          <div class="range range-40">
            <div class="cell-md-6 cell-lg-7">
              <div class="object">
                <div class="object-left">
                </div>
              </div>
              <div class="block-text-width">
                <div class="block-text-width-divider-content">

                  <div class="quote-demo">
                    <h4 class="quote-demo-title"><%=@message.title%></h4>
                  </div>
                  <p class="text-spacing-0"><%=@message.content%></p>
                  <div class="single-post-meta">
                    <div class="single-post-meta-item">
                      <ul class="list-inline list-inline-lg">
                        <li>
                          <div class="object-inline text-spacing-0 text-gray-darker"><span>Posté le <%=@message.created_at.strftime("%d.%m.%Y") %></span></div>
                        </li>
                        <li>
                          <div class="object-inline text-spacing-0 text-gray-darker"><span><%=@profile.pseudo.capitalize%></span></div>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <%@messagecommits = Messagecommit.where(message_id: @message.id) %>
              <div class="comment-wrap">
                <div class="comment-wrap-title heading-4"><span><%=@messagecommits.length%> commentaire(s)</span></div>
                <!-- Comment 1st level-->
                <% @messagecommits.each do |commit|%>
                   <% @user = User.where(email: commit.autor)%>
                   <%@profilecommit = Profile.where(user_id: @user.last.id)%>
                <div class="comment">
                  <div class="comment-inner">
                    <div class="comment-left">
                      <% if @profilecommit.last.photo.nil? %>
                        <img class ="img-circle" src="https://res.cloudinary.com/dz83jh064/image/upload/v1517825470/images_z0whi1.png" size="80*80" crop="fill" alt="" />
                      <% else %>
                        <%= cl_image_tag @profilecommit.last.photo, class:"img-circle", size:"80x80", crop:"fill", alt:""%>
                      <% end %>


                    </div>
                    <div class="comment-body">
                      <div class="comment-body-header">
                        <div class="comment-name"><%=@profilecommit.last.pseudo.capitalize%></div>
                        <div class="comment-time"><%=commit.created_at.strftime("%d.%m.%Y") %></div>
                      </div>
                      <div class="comment-body-content">
                        <p class="text-spacing-50"><%=commit.content%></p>
                        <ul class="list-inline list-inline-lg">
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                <% end %>
                <!-- Comment 1st level-->


                <% @messagecommit = Messagecommit.new %>
                <%= simple_form_for [@message, @messagecommit], class: 'login-box' do |f| %>


                <!-- Comment 1st level-->
                <div class="comment">
                  <div class="comment-inner">
                    <div class="comment-left">
                      <% if current_user.profile.photo.nil? %>
                        <img class ="img-circle" src="https://res.cloudinary.com/dz83jh064/image/upload/v1517825470/images_z0whi1.png" size="80x80" crop="fill" alt=""/>
                      <% else %>
                        <%= cl_image_tag current_user.profile.photo, size:"80x80", crop:"fill", alt:"", class:"img-circle"%>
                      <% end %>


                    </div>
                    <div class="comment-body" style="width: 100%">
                      <div class="comment-body-header">
                        <div class="comment-name"><%=current_user.profile.pseudo.capitalize %></div>
                      </div>
                      <div class="comment-body-content">


                        <form class="rd-mailform" data-form-output="form-output-global" data-form-type="contact" method="post">
                          <div class="form-wrap form-wrap-validation">

                            <%= f.input :content , :as => :text, input_html: {style: 'max-height:1500px;'}, required: true,label: false, class: "form-control form-control-last-child", placeholder:"Écrivez ici" %>

                          </div>
                          <div class="form-button">
                            <button class="button button-effect-ujarak button-primary" type="submit">Poster</button>
                          </div>
                        </form>


                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

<% end %>
            <div class="cell-md-4 cell-lg-3">
              <div class="blog-aside">
                <div class="range range-40 range-lg-60">
                  <div class="cell-md-10 blog-aside-item">
                    <div class="rd-navbar-search">

                    </div>
                  </div>

                  <div class="cell-md-10 blog-aside-item">
                    <div class="blog-aside-item-inner">
                      <h4 class="text-center">Derniers Messages</h4>
                      <div class="post-minimal-wrap"><a class="post-minimal" href="#">
                          <% @messages.where(statut: 'yes').order("created_at DESC").first(3).each do |message| %>
                            <% @profile = Profile.find(message.profile_id)  %>
                            <%@messagecommits = Messagecommit.where(message_id: message.id) %>

                            <div class="unit unit-spacing-xs unit-horizontal">
                              <div class="unit-left">
                                <img src="https://images.unsplash.com/photo-1522074534099-45b66be3f193?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1120af654449ab8c8e2247989f0bff2f&auto=format&fit=crop&w=1234&q=80" alt="" width="92" height="78" class="img-responsive center-block"/>
                              </div>
                              <div class="unit-body">
                                <p><%= link_to message.title, profile_message_path(@profile, message)%> <span><%= message.created_at.strftime("%d.%m.%Y")%> / <%=@messagecommits.length%> commentaire(s)</span></p>
                              </div>
                            </div>
                          </a>
                          <a class="post-minimal" href="#">
                            <% end %>
                        </a>
                      </div>
                    </div>
                  </div>

                  <div class="cell-sm-5 cell-md-10 blog-aside-item text-center">
                    <div class="blog-aside-item-inner">
                        <a href="<%=root_path %>"><button  class="button button-effect-ujarak button-primary button-block" type="submit">Accueil</button></a>
                        <br/>
                        <a href="<%=messages_path %>"><button  class="button button-effect-ujarak button-primary button-block" type="submit">Le forum</button></a>
                    </div>
                  </div>



                </div>
              </div>
            </div>
          </div>
        </div>
      </section>


    </div>
    <!-- PANEL-->
    <!-- END PANEL-->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>