config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles do
    resources :articles
    resources :messages
    resources :conversations

  end


  resources :messages do
    resources :messagecommits
  end
  resources :articles do
    resources :articlecommits
  end
  resources :contacts
resources :conversations do
    resources :conversationcommits
  end
  get 'pages/pourquoi'
  get 'pages/info'
  get 'pages/liens'
  get 'pages/admin'
  get 'pages/mention'
  get 'pages/test'
  get 'valider_profile', to: 'profiles#valider_profile'
  get 'refuser_profile', to: 'profiles#refuser_profile'
  get 'valider_article', to: 'articles#valider_article'
  get 'refuser_article', to: 'articles#refuser_article'
  get 'effacer_contact', to: 'contacts#effacer_contact'
  get 'bloquer_profile', to: 'profiles#bloquer_profile'

  get 'rendre_admin', to: 'profiles#rendre_admin'
  get 'rendre_nonadmin', to: 'profiles#rendre_nonadmin'


  get 'supprimer_profile', to: 'profiles#supprimer_profile'
  get 'debloquer_profile', to: 'profiles#debloquer_profile'
  get 'supprimer_conversation', to: 'conversations#supprimer_conversation'
  get 'supprimer_notification', to: 'notifications#supprimer_notification'

  get 'pages/notification'

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :conversations, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :messagecommits, through: :messages, dependent: :destroy
  has_many :articlecommits, through: :articles, dependent: :destroy
  has_many :conversationcommits, through: :conversations, dependent: :destroy

  mount_uploader :photo, PhotoUploader
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def show
    @profile = Profile.find(params[:id])
    @articles = Article.where(profile_id: @profile.id, statut: 'yes')
    @messages = Message.where(profile_id: @profile.id, statut: 'yes')
  end

  def index
    @profiles = Profile.where(statut: "yes")
  end


  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    @profile.statut = "no"
    if @profile.save
      flash[:notice] = 'Votre profil a correctement été créé. Il sera validé par un admin, merci.'
      redirect_to root_path
    else
      flash[:notice] = 'Un problème est survenu lors de la création de votre profil.'
      redirect_to new_profile_path
    end
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      flash[:notice] = 'Votre profil a correctement été actualisé. Merci.'
      redirect_to profile_path(@profile)
    else
      flash[:notice] = 'Un problème est survenu lors de la mise à jour de votre profil.'
      redirect_to profile_path(@profile)
    end
  end

 def valider_profile
    @profile = Profile.find(params[:profileid])
    @profile.statut = "yes"
    @profile.save
    flash[:notice] = "Le profil a été validé. Merci."
    redirect_to pages_admin_path
  end

  def refuser_profile
    @profile = Profile.find(params[:profileid])
    @user = User.where(id: @profile.user_id)
    @user.last.destroy
    flash[:alert] = "Le profil a été refusé et effacé de la base de donnée."
    redirect_to pages_admin_path
  end

  def bloquer_profile
    @profile = Profile.find(params[:profileid])
    @profile.statut = "bloqué"
    @profile.save
    flash[:notice] = "Le profil a été bloqué. Merci."
    redirect_to profiles_path
  end

  def supprimer_profile
    @profile = Profile.find(params[:profileid])
    @user = User.find(@profile.user_id)
    @user.destroy
    flash[:alert] = "Le profil a été effacé de la base de donnée ainsi que son contenu."
    redirect_to profiles_path
  end

  def debloquer_profile
    @profile = Profile.find(params[:profileid])
    @profile.statut = "yes"
    @profile.save
    flash[:notice] = "Le profil a été débloqué. Merci."
    redirect_to profiles_path
  end

  def rendre_admin

    @profile = Profile.find(params[:profileid])
    @profile.admin = "yes"
    @profile.save
    flash[:notice] = "Le profil a mis en admin. Merci."
    redirect_to profiles_path

  end

  def rendre_nonadmin

    @profile = Profile.find(params[:profileid])
    @profile.admin = "no"
    @profile.save
    flash[:notice] = "Le profil a mis en admin. Merci."
    redirect_to profiles_path

  end

  private

  def profile_params
  params.require(:profile).permit(:first_name, :last_name, :job, :city, :phone_number, :birthday, :photo, :photo_cache, :statut, :pseudo, :biography)
  end
end

app/views/profiles/edit.html.erb
<div class="text-left page">
      <section class="section section-breadcrumb">
        <div class="parallax-container breadcrumb-wrapper" data-parallax-img="https://images.unsplash.com/photo-1525167753025-08f17bdddb7f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=679dd1936d7c0bdb8f3682cf4f98108c&auto=format&fit=crop&w=2850&q=80">
          <div class="parallax-content section-lg context-dark">
            <div class="shell context-dark">

            </div>
          </div>
        </div>
      </section>
      <section class="section section-lg bg-white text-center">
        <div class="shell">
          <div class="range range-xs-center range-60 range-lg-200">
            <div class="cell-xs-12">
              <div class="block-center" style="max-width: 520px">
                <h3>Modifier mon profil</h3>
                <p>Un profil enregistré permet de pouvoir communiquer avec les autres et ainsi profiter pleinement du site.</p>
              <%= simple_form_for @profile do |f| %>
              <form class="rd-mailform block-center" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php" style="max-width: 584px">
                <div class="range range-xs-center range-20 range-narrow">
                  <div class="cell-sm-5">
                    <div class="form-wrap form-wrap-validation">
                      <%= f.input :last_name, label: "Nom", class: "form-input", id: "forms-name", required: true, autofocus: true %>
                    </div>
                  </div>
                  <div class="cell-sm-5">
                    <div class="form-wrap form-wrap-validation">
                      <%= f.input :first_name, label: "Prénom", class: "form-input", id: "forms-name", required: true, autofocus: true %>
                    </div>
                  </div>
                  <div class="cell-sm-5">
                    <div class="form-wrap form-wrap-validation">
                      <%= f.input :job, label: "Profession", class: "form-input", id: "forms-name", required: true, autofocus: true %>
                    </div>
                  </div>
                  <div class="cell-sm-5">
                    <div class="form-wrap form-wrap-validation">
                      <%= f.input :city, label: "Ville", class: "form-input", id: "forms-name", required: true, autofocus: true %>

                    </div>
                  </div>

                  <div class="cell-sm-5">
                    <div class="form-wrap form-wrap-validation">
                      <%= f.input :phone_number, label: "Portable", class: "form-input", id: "forms-name", required: true, autofocus: true %>

                    </div>
                  </div>
                  <div class="cell-sm-5">
                    <div class="form-wrap form-wrap-validation">
                      <%= f.input :birthday, as: :date, html5: true,  class: "form-input", id: "forms-name", label:"Date de naissance" %>

                    </div>
                  </div>
                  <div class="cell-sm-5">
                    <div class="form-wrap form-wrap-validation">
                      <%= f.input :pseudo, label: "Pseudo", class: "form-input", id: "forms-name", required: true, autofocus: true %>

                    </div>
                  </div>
                  <div class="cell-sm-5">
                    <div class="form-wrap form-wrap-validation">
                      <%= f.input :photo, class: "form-control", label:"Photo"%>
                      <%= f.input :photo_cache, as: :hidden %>
                    </div>
                  </div>
                        <div class="cell-sm-10">
                    <div class="form-wrap form-wrap-validation">

                        <%= f.input :biography , input_html: {style: 'max-height:1500px;'}, required: true, class: "form-control form-control-last-child", label:"Biographie" %>
                    </div>
                  </div>

                  <div class="cell-sm-5">
                    <div class="form-button">
                      <a href="<%=pages_mention_path%>" target="_blank">Merci de lire les mentions légales</a>
                      <button class="button button-effect-ujarak button-primary button-block button-square" type="submit">modifier</button>
                    </div>
                  </div>
                </div>
              </form>
              <% end %>

              <!-- RD Mailform-->


              <div class="block-center" style="max-width: 675px">

              </div>

              <div class="block-center" style="max-width: 675px">

              </div>
            </div>
          </div>
        </div>
      </section>

      <div class="divider-section"></div>
      <!-- Page Footer-->

      <footer class="page-footer section text-center">
        <div class="shell shell-out">
          <div class="range range-xs-reverse range-10">
            <div class="cell-xs-4 cell-sm-4 text-xs-right">
              <div class="preffix-xl-70" style="max-width: 433px">
                <ul class="list-inline">
                  <li><a class="icon icon-gray-darker fa-facebook" href="#"></a></li>
                  <li><a class="icon icon-gray-darker fa-twitter" href="#"></a></li>
                  <li><a class="icon icon-gray-darker fa-google-plus" href="#"></a></li>
                  <li><a class="icon icon-gray-darker fa-pinterest-p" href="#"></a></li>
                </ul>
              </div>
            </div>
            <div class="cell-xs-6 cell-sm-6 text-xs-left">
              <p class="copyright preffix-xl-70">Clinic &#169; <span class="copyright-year"></span>. <a href="privacy-policy.html">Privacy Policy</a>
              </p>
            </div>
          </div>
        </div>
      </footer>
    </div>
    <!-- PANEL-->
    <!-- END PANEL-->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->

app/views/profiles/index.html.erb
    <div class="text-left page">
      <!-- Page preloader-->
      <div class="page-loader">
        <div>
          <div class="page-loader-body">
            <svg x="0" y="0" width="258" height="258">


            </svg>
          </div>
        </div>
      </div>
      <!-- Page Header-->

      <!-- Clients-->
      <section class="section section-breadcrumb">
        <div class="parallax-container breadcrumb-wrapper" data-parallax-img="https://images.unsplash.com/photo-1469510038946-6bf892bbe9d6?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7e36e818e6298b397fbf864346fdf731&auto=format&fit=crop&w=2850&q=80">
          <div class="parallax-content section-lg context-dark">
            <div class="shell context-dark">
              <h2>Les membres de Médentraid</h2>
              <div class="divider"></div>
            </div>
          </div>
        </div>

      </section>

       <br/>
    <br/>
    <div class="container">
<i>Sur cette page vous aurez la possibilité de voir la liste des inscrits . Pour voir leur profil, veuillez cliquer sur leur pseudo. Pour les contacter en privé, veuillez cliquer sur le bouton "contacter" en bas du membre choisi. Les messages envoyés seront vivibles dans la rubrique "messagerie interne" du menu "mon compte" de la barre de navigation . </i>
 <div class="divider"></div>
      <section class="section section-lg bg-white text-left">
        <div class="shell">
          <div class="range range-60">
            <div class="cell-lg-8">
              <div class="range range-35">



                <% @profiles.each do |profile| %>

                <% userprofile = User.where(id: profile.user_id)%>
                <div class="cell-xs-5 cell-sm-33 cell-md-25">
                  <div class="vip">
                    <div class="vip-image-block">

                      <% if profile.photo_url.nil? %>
                      <img src="https://res.cloudinary.com/dz83jh064/image/upload/v1517825470/images_z0whi1.png" size="300*250" crop="fill" alt="" />
                      <% else %>
                      <%= cl_image_tag profile.photo, size:"300x250", crop:"fill", alt:""%>
                      <% end %>

                    </div>
                    <div class="vip-content">
                      <h5><a href="<%=profile_path(profile.id)%>"><%= profile.pseudo.capitalize %></a></h5>
                      <div class="vip-cite"><span><%=profile.job.upcase%></span></div>
                      <div class="vip-divider"></div>
                      <% now = Date.current %>
                      <% age = now.year - profile.birthday.year %>
                      <% age -= 1 if now.yday < profile.birthday.yday %>
                      <div class="vip-link"><span class="fas fa-birthday-cake"></span> <%= age%> ans</div>
                    </div>
                    <br/>
                    <a href="<%=new_profile_conversation_path(current_user.profile.id, dest: userprofile.last.email)%>"%><button class="button button-effect-ujarak button-primary button-shadow button-circle">Contacter</button></a>
                    <% if current_user && current_user.profile && current_user.profile.admin == "yes" && profile.admin != "yes"%>
                      <%= link_to 'Bloquer', bloquer_profile_path(profileid: profile.id), class:"button button-effect-ujarak button-primary button-block"%>
                      <%= link_to 'Rendre Admin', rendre_admin_path(profileid: profile.id), class:"button button-effect-ujarak button-primary button-block"%>
                      <%= link_to 'Supprimer', supprimer_profile_path(profileid: profile.id), class:"button button-effect-ujarak button-primary button-block"%>
                    <% elsif current_user && current_user.profile && current_user.profile.admin == "yes" && profile.admin != "no"%>
                      <%= link_to 'Enlever Admin', rendre_nonadmin_path(profileid: profile.id), class:"button button-effect-ujarak button-primary button-block"%>

                    <% end %>

                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- Page Footer-->
      <section class="section section-sm bg-white-lighter">
        <div class="shell shell-out">
          <div class="range range-30">
            <div class="cell-sm-3 cell-xs-5">
              <div class="preffix-xl-70" style="max-width: 274px">
                <h6 class="text-spacing-200 text-uppercase font-base">Derniers inscrits</h6>

                <div class="divider-modern"></div>
                <ul class="list list-md">
                  <% @profiles.where(statut: 'yes').order("created_at DESC").first(3).each do |profile| %>

                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"><span class="far fa-address-card"></span></div>
                      <div class="unit-body"><a class="link-gray-darker" href="<%=profile_path(profile.id) %>"><%=profile.pseudo.capitalize%> inscrit le <%=profile.created_at.strftime("%d.%m.%Y") %></a></div>
                    </div>
                  </li>
                  <% end %>


                </ul>
              </div>
            </div>
            <div class="cell-sm-3 cell-xs-5">
              <div class="preffix-xl-70" style="max-width: 274px">

                <ul class="list list-md">


                </ul>
              </div>
            </div>
            <div class="cell-sm-4">
              <div class="preffix-xl-70" style="max-width: 433px">


                <ul class="list-inline list-inline-lg">
                  <a href="<%=root_path%>"><button  class="button button-effect-ujarak button-white button-shadow button-circle">Accueil</button></a>
                  <br/>
                  <br/>
                  <a href="<%=profile_path(current_user.profile.id)%>"><button class="button button-effect-ujarak button-primary button-shadow button-circle">Mon profil</button></a>

                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

    </div>
    <!-- PANEL-->
    <!-- END PANEL-->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->

app/views/profiles/show.html.erb
    <!-- Page-->
    <div class="text-left page">
      <!-- Page preloader-->
      <div class="page-loader">
        <div>
          <div class="page-loader-body">
            <svg x="0" y="0" width="258" height="258">


            </svg>
          </div>
        </div>
      </div>


      <section class="section section-lg bg-white text-left">
        <div class="shell">
          <div class="range range-30">
            <div class="cell-sm-5">
              <% if @profile.photo_url.nil? %>
                      <img src="https://res.cloudinary.com/dz83jh064/image/upload/v1517825470/images_z0whi1.png" size="300*250" crop="fill" alt="" />
                      <% else %>
                      <%= cl_image_tag @profile.photo, size:"300x250", crop:"fill", alt:""%>
                      <% end %>
              <div class="block-text-width-divider">
                <div class="block-text-width-divider-content">
                  <p class="text-gray-darker"><%= @profile.biography %></p>

                </div>
              </div>
            </div>
            <div class="cell-sm-5">
              <div class="single-block">
                <% if current_user.id == @profile.user_id %>
                <h3>Profil de  <%= @profile.first_name.capitalize%> <%= @profile.last_name.upcase%></h3>
                <% else %>
                <h3>Profil de <%= @profile.pseudo.capitalize %> </h3>
                <% end %>
                <p><%=@profile.job.capitalize%></p>

                <% if current_user.id == @profile.user_id %>


                <ul class="list-inline">
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"></div>
                      <div class="unit-body"><i class="link-gray-darker" >Tél: <%=@profile.phone_number%></i></div>
                    </div>
                  </li>
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"></div>
                      <div class="unit-body" style="position: relative; top: 1px"><i class="link-gray-darker text-spacing-0" >Mail: <%= current_user.email%></i></div>
                    </div>
                  </li>
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"></div>
                      <div class="unit-body" style="position: relative; top: 1px"><i class="link-gray-darker text-spacing-0" >Ville: <%= @profile.city.upcase%></i></div>
                    </div>
                  </li>
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"></div>
                      <div class="unit-body" style="position: relative; top: 1px"><i class="link-gray-darker text-spacing-0" >Pseudo: <%= @profile.pseudo%></i></div>
                    </div>
                  </li>
                  <% now = Date.current %>
                  <% age = now.year - @profile.birthday.year %>
                  <% age -= 1 if now.yday < @profile.birthday.yday %>

                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"></div>
                      <div class="unit-body" style="position: relative; top: 1px"><i class="link-gray-darker text-spacing-0" >Age: <%= age%> ans</i></div>
                    </div>
                  </li>
                </ul>
                <div class="group group-xl group-middle group-center">

                  <%= link_to 'Modifier', edit_profile_path(current_user.profile.id) , class:"button button-effect-ujarak button-primary button-shadow button-circle"%>
                  <%= link_to 'Accueil', root_path , class:"button button-effect-ujarak button-white button-shadow button-circle"%>
                  <a href="<%=profiles_path%>"><button class="button button-effect-ujarak button-white button-shadow button-circle">Les inscrits</button></a>

                  <% if current_user && current_user.profile && current_user.profile.admin == "yes" %>
                  <%= link_to 'Interface Admin', pages_admin_path , class:"button button-effect-ujarak button-white button-shadow button-circle"%>
                  <% end %>
                </div>


                <% else %>

                 <ul class="list-inline">

                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"></div>
                      <div class="unit-body" style="position: relative; top: 1px"><i class="link-gray-darker text-spacing-0" >Ville: <%= @profile.city.upcase%></i></div>
                    </div>
                  </li>
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"></div>
                      <div class="unit-body" style="position: relative; top: 1px"><i class="link-gray-darker text-spacing-0" >Pseudo: <%= @profile.pseudo%></i></div>
                    </div>
                  </li>
                  <% now = Date.current %>
                  <% age = now.year - @profile.birthday.year %>
                  <% age -= 1 if now.yday < @profile.birthday.yday %>

                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"></div>
                      <div class="unit-body" style="position: relative; top: 1px"><i class="link-gray-darker text-spacing-0" >Age: <%= age%> ans</i></div>
                    </div>
                  </li>
                </ul>
                <% @user = User.where(id: @profile.user_id)%>
                <div class="group group-xl group-middle group-center">
                  <a href="<%=new_profile_conversation_path(current_user.profile.id, dest: @user.last.email)%>"%><button class="button button-effect-ujarak button-primary button-shadow button-circle">Contacter</button></a>
                  <a href="<%=root_path%>"><button class="button button-effect-ujarak button-white button-shadow button-circle">Accueil</button></a>
                  <a href="<%=profiles_path%>"><button class="button button-effect-ujarak button-white button-shadow button-circle">Les inscrits</button></a>

                </div>



                <% end %>

              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- Page Footer-->
      <section class="section section-sm bg-white-lighter">
        <div class="shell shell-out">
          <div class="range range-30">
            <div class="cell-sm-3 cell-xs-5">
              <div class="preffix-xl-70" style="max-width: 274px">
                <h6 class="text-spacing-200 text-uppercase font-base">Derniers articles du membre <%= @profile.pseudo.capitalize%></h6>

                <div class="divider-modern"></div>
                <ul class="list list-md">
                <% @lastarticles = Article.where(profile_id: @profile.id)%>
                <% @lastarticles.where(statut: 'yes').order("created_at DESC").first(3).each do |article| %>
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"><span class="icon icon-md icon-primary mdi-phone"></span></div>
                      <div class="unit-body"><%= link_to article.title, profile_article_path(article.profile_id,article.id), class:"link-gray-darker"%></div>
                    </div>
                  </li>
                  <%end%>


                </ul>
              </div>
            </div>
            <div class="cell-sm-3 cell-xs-5">
              <div class="preffix-xl-70" style="max-width: 274px">
                <h6 class="text-spacing-200 text-uppercase font-base">Derniers messages du membre <%= @profile.pseudo.capitalize%></h6>
                <div class="divider-modern"></div>
                <ul class="list list-md">
                <% @lastmessages = Message.where(profile_id: @profile.id)%>
                <% @lastmessages.where(statut: 'yes').order("created_at DESC").first(3).each do |message| %>

                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal">
                      <div class="unit-left"><span class="icon icon-md-biger icon-primary mdi-map-marker"></span></div>
                      <div class="unit-body" style="position: relative; top: -4px;"><a class="link-default" href="#"><%= link_to message.title, profile_message_path(message.profile_id, message.id), class:"link-default"%></a></div>

                    </div>
                  </li>

                  <% end %>
                </ul>
              </div>
            </div>
                <% if current_user.id == @profile.user_id %>

            <div class="cell-sm-4">
              <div class="preffix-xl-70" style="max-width: 433px">
                <h6 class="text-spacing-200 text-uppercase font-base">Effacer mon compte</h6>
                <div class="divider-modern"></div>
                <p>Vous pouvez à tout moment effacer votre compte ainsi que vos posts. Attention car cette manoeuvre est irréversible!!!</p>
              </br>

              <%= link_to 'Effacer', supprimer_profile_path(profileid: current_user.id), class:"button button-effect-ujarak button-primary button-shadow button-circle"%>

              </div>
            </div>
            <% end %>
          </div>
        </div>
      </section>

    </div>
    <!-- PANEL-->
    <!-- END PANEL-->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->