config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles do
    resources :articles
    resources :messages
    resources :conversations

  end


  resources :messages do
    resources :messagecommits
  end
  resources :articles do
    resources :articlecommits
  end
  resources :contacts
resources :conversations do
    resources :conversationcommits
  end
  get 'pages/pourquoi'
  get 'pages/info'
  get 'pages/liens'
  get 'pages/admin'
  get 'pages/mention'
  get 'pages/test'
  get 'valider_profile', to: 'profiles#valider_profile'
  get 'refuser_profile', to: 'profiles#refuser_profile'
  get 'valider_article', to: 'articles#valider_article'
  get 'refuser_article', to: 'articles#refuser_article'
  get 'effacer_contact', to: 'contacts#effacer_contact'
  get 'bloquer_profile', to: 'profiles#bloquer_profile'

  get 'rendre_admin', to: 'profiles#rendre_admin'
  get 'rendre_nonadmin', to: 'profiles#rendre_nonadmin'


  get 'supprimer_profile', to: 'profiles#supprimer_profile'
  get 'debloquer_profile', to: 'profiles#debloquer_profile'
  get 'supprimer_conversation', to: 'conversations#supprimer_conversation'
  get 'supprimer_notification', to: 'notifications#supprimer_notification'

  get 'pages/notification'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
      <footer class="page-footer-full section section-full-width">
        <div class="shell">
          <div class="range range-15">
            <div class="cell-sm-5">
              <p class="copyright">MÉDENTRAID &#169; <span class="copyright-year"></span>. <a href="<%=pages_mention_path%>">Mentions légales</a>
              </p>
            </div>
            <div class="cell-sm-5 text-sm-right">
              <ul class="list-inline">

              </ul>
            </div>
          </div>
        </div>
      </footer>

app/views/shared/_navbar.html.erb
<header class="page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar rd-navbar-minimal" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-static" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-static" data-md-stick-up-offset="40px" data-lg-stick-up-offset="40px" data-stick-up="true" data-sm-stick-up="true" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-inner">
              <!-- RD Navbar Panel-->
              <div class="rd-navbar-panel">
                <!-- RD Navbar Toggle-->
                <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                <!-- RD Navbar Brand-->
                <div class="rd-navbar-brand"><a class="brand-name" href="<%=root_path%>"><img src="https://res.cloudinary.com/dz83jh064/image/upload/v1629279673/Medentraid_logo_gxrazg.png" alt="" width="79" height="92"/></a></div>
              </div>
              <div class="rd-navbar-aside-right">
                <div class="rd-navbar-nav-wrap">
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li><a href="/">Accueil</a></li>
                    <li><a href="<%=pages_pourquoi_path%>">Pourquoi?</a></li>
                    <li><a href="<%=pages_info_path%>">Infos</a><li>

                    <% if current_user.present?%>

                    <li class="active"><a href="#">Mon compte</a>

                      <% if current_user.profile &&  current_user.profile.statut == "yes"%>
                      <!-- RD Navbar Megamenu-->
                      <ul class="rd-navbar-megamenu">

                        <li class="rd-navbar-megamenu-item">
                          <div class="rd-navbar-megamenu-item-inner">
                            <h6 class="rd-navbar-megamenu-title">Mes options</h6>
                            <div class="rd-navbar-megamenu-divider"></div>
                            <ul class="notification-badges">
                              <li><%= link_to 'Mon profil', profile_path(current_user.profile.id)%></li>
                              <li><%= link_to 'Le forum', messages_path%></li>
                              <li><%= link_to 'Les articles', articles_path%></li>
                              <li><%= link_to 'Les inscrits', profiles_path%></li>
                              <li><%= link_to 'Ma messagerie privée', conversations_path%></li>
                              <% @nombre = Notification.where(dest: current_user.email)%>
                              <li data-badge="<%=@nombre.count%>"><%= link_to 'Mes notifications', pages_notification_path%></li>


                              <li> <%= link_to destroy_user_session_path, method: :get do %>
                                <%= t(".sign_out", default: "Se déconnecter") %>
                                <% end %>
                              </li>
                            </ul>
                          </div>
                        </li>
                      </ul>
                      <% elsif current_user.profile &&  current_user.profile.statut == "bloqué"%>
                        <ul class="rd-navbar-megamenu">

                        <li class="rd-navbar-megamenu-item">
                          <div class="rd-navbar-megamenu-item-inner">
                            <h6 class="rd-navbar-megamenu-title">Mes options</h6>
                            <div class="rd-navbar-megamenu-divider"></div>
                            <ul>
                              <li><i>Votre profil a été bloqué, veuillez contacter l'équipe.</i></li>

                              <li> <%= link_to destroy_user_session_path, method: :get do %>
                                <%= t(".sign_out", default: "Se déconnecter") %>
                                <% end %>
                              </li>
                            </ul>
                          </div>
                        </li>
                      </ul>
                      <% elsif ! current_user.profile%>
                      <ul class="rd-navbar-megamenu">

                        <li class="rd-navbar-megamenu-item">
                          <div class="rd-navbar-megamenu-item-inner">
                            <h6 class="rd-navbar-megamenu-title">Mes options</h6>
                            <div class="rd-navbar-megamenu-divider"></div>
                            <ul>
                              <li><%= link_to 'créer mon profil', new_profile_path%></li>
                             <li> <%= link_to destroy_user_session_path, method: :get do %>
                                <%= t(".sign_out", default: "Se déconnecter") %>
                                <% end %>
                              </li>
                            </ul>
                          </div>
                        </li>
                      </ul>

                      <% else %>
                      <ul class="rd-navbar-megamenu">

                        <li class="rd-navbar-megamenu-item">
                          <div class="rd-navbar-megamenu-item-inner">
                            <h6 class="rd-navbar-megamenu-title">Mes options</h6>
                            <div class="rd-navbar-megamenu-divider"></div>
                            <ul>
                              <li><i>Votre profil n'a pas encore été validé pour profiter des services.</i></li>

                              <li> <%= link_to destroy_user_session_path, method: :get do %>
                                <%= t(".sign_out", default: "Se déconnecter") %>
                                <% end %>
                              </li>
                            </ul>
                          </div>
                        </li>
                      </ul>
                    <% end %>

                    </li>

                    <% else %>
                    <li><a href="<%=new_user_session_path%>">Se connecter</a></li>

                    <% end%>
                    <li><a href="<%=pages_liens_path%>">Liens utiles</a></li>
                  </ul>
                </div>
              </div>
              <div class="rd-navbar-search"><span class="rd-navbar-search-tooltip"></span>
              </div>
            </div>
          </nav>
        </div>
      </header>