config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles do
    resources :articles
    resources :messages
    resources :conversations

  end


  resources :messages do
    resources :messagecommits
  end
  resources :articles do
    resources :articlecommits
  end
  resources :contacts
resources :conversations do
    resources :conversationcommits
  end
  get 'pages/pourquoi'
  get 'pages/info'
  get 'pages/liens'
  get 'pages/admin'
  get 'pages/mention'
  get 'pages/test'
  get 'valider_profile', to: 'profiles#valider_profile'
  get 'refuser_profile', to: 'profiles#refuser_profile'
  get 'valider_article', to: 'articles#valider_article'
  get 'refuser_article', to: 'articles#refuser_article'
  get 'effacer_contact', to: 'contacts#effacer_contact'
  get 'bloquer_profile', to: 'profiles#bloquer_profile'

  get 'rendre_admin', to: 'profiles#rendre_admin'
  get 'rendre_nonadmin', to: 'profiles#rendre_nonadmin'


  get 'supprimer_profile', to: 'profiles#supprimer_profile'
  get 'debloquer_profile', to: 'profiles#debloquer_profile'
  get 'supprimer_conversation', to: 'conversations#supprimer_conversation'
  get 'supprimer_notification', to: 'notifications#supprimer_notification'

  get 'pages/notification'

end

app/views/pages/admin.html.erb
    <div class="text-left page">
      <!-- Page preloader-->
      <div class="page-loader">
        <div>
          <div class="page-loader-body">
            <svg x="0" y="0" width="258" height="258">

              <clippath id="clip-path">

              </clippath>
            </svg>
          </div>
        </div>
      </div>
      <!-- Page Header-->
      <section class="section section-breadcrumb">
        <div class="parallax-container breadcrumb-wrapper" data-parallax-img="https://images.unsplash.com/uploads/141103282695035fa1380/95cdfeef?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=cf56dd62f7e28facff79eaf6e7a78df4&auto=format&fit=crop&w=3074&q=80">
          <div class="parallax-content section-lg context-dark">
            <div class="shell context-dark">
              <h2>Bienvenue <%=current_user.profile.first_name.capitalize%> sur votre page Admin</h2>
              <div class="divider"></div>
            </div>
          </div>
        </div>
      </section>

      <section class="section section-lg bg-white text-center">
        <div class="shell">
          <h3>Interface ADMIN</h3>
          <p class="large block-md-big">Dans cette page vous pourrez accepter ou non une demande d'inscription, la diffusion d'un article. Vous pourrez également voir les messages envoyés par les non-inscrits.</p>

          <div class="range range-xs-center">
            <div class="cell-sm-10 cell-lg-9 cell-xl-8">

              <div class="divider-edgewise"></div>


              <h4>Les demandes d'inscriptions en attente</h4>
                    <% @profileattempts = Profile.where(statut: "no")%>
              <% if @profileattempts.length == 0 %>
              <i>Pas de demande en attente </i>
              <% else %>

              <div class="table-custom-responsive">
                <table class="table-custom table-custom-primary">
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Nom - Prénom</th>
                      <th>e-mail</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @profileattempts.each do |profile|%>
                    <% @userattempt = User.where(id: profile.user_id)%>
                    <tr>
                      <td><%= profile.created_at.strftime("%d.%m.%Y") %></td>
                      <td><%=profile.last_name.upcase%> <%=profile.first_name.capitalize%></td>
                      <td><%=@userattempt.last.email%></td>
                      <td>
                         <%= link_to 'Accepter',  valider_profile_path(profileid: profile.id) , class:"button button-effect-ujarak button-primary button-block"%>
                        <%= link_to 'Refuser', refuser_profile_path(profileid: profile.id) , class:"button button-effect-ujarak button-primary button-block"%>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>

              <% end %>


              <div class="divider-edgewise"></div>

              <h4>Les demandes de parution d'articles</h4>
                    <% @articleattempts = Article.where(statut: "no")%>
              <% if @articleattempts.length == 0 %>
              <i>Pas de demande en attente </i>
              <% else %>

              <div class="table-custom-responsive">
                <table class="table-custom table-custom-primary">
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Auteur</th>
                      <th>Titre</th>
                      <th>Contenu</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @articleattempts.each do |article|%>
                    <% @profilearticle = Profile.where(id: article.profile_id)%>
                    <tr>
                      <td><%= article.created_at.strftime("%d.%m.%Y") %></td>
                      <td><%=@profilearticle.last.last_name.upcase%> <%=@profilearticle.last.first_name.capitalize%></td>
                      <td><%=article.title%></td>
                      <td><%=article.content%></td>
                      <td>
                         <%= link_to 'Accepter', valider_article_path(articleid: article.id), class:"button button-effect-ujarak button-primary button-block"%>
                        <%= link_to 'Refuser', refuser_article_path(articleid: article.id) , class:"button button-effect-ujarak button-primary button-block"%>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>

              <% end %>


              <div class="divider-edgewise"></div>



              <h4>Les demandes de contact externes</h4>
                    <% @contacts = Contact.all%>
              <% if @contacts.length == 0 %>
              <i>Pas de demande en ce moment </i>
              <% else %>

              <div class="table-custom-responsive">
                <table class="table-custom table-custom-primary">
                  <thead>
                    <tr>

                      <th>Email</th>
                      <th>Message</th>

                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @contacts.each do |contact|%>

                    <tr>

                      <td><%=contact.email%></td>
                      <td><%=contact.content%></td>

                      <td>
                         <%= link_to 'Effacer', effacer_contact_path(contactid: contact.id), class:"button button-effect-ujarak button-primary button-block"%>

                      </td>
                    </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>
            <% end %>
              <div class="divider-edgewise"></div>

             <h4>Les comptes bloqués</h4>
                    <% @comptes = Profile.where(statut: "bloqué")%>
              <% if @comptes.length == 0 %>
              <i>Pas de compte bloqué en ce moment </i>
              <% else %>

              <div class="table-custom-responsive">
                <table class="table-custom table-custom-primary">
                  <thead>
                    <tr>

                      <th>Nom - Prenom</th>


                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @comptes.each do |compte|%>

                    <tr>

                      <td><%=compte.last_name.upcase%> <%=compte.first_name.capitalize%></td>


                      <td>
                         <%= link_to 'Débloquer', debloquer_profile_path(profileid: compte.id), class:"button button-effect-ujarak button-primary button-block"%>

                      </td>
                    </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>
            <% end %>




            </div>
          </div>
        </div>
      </section>

      <!-- Page Footer-->
     <section class="section section-sm bg-white-lighter">
        <div class="shell shell-out">
          <div class="range range-30">
            <div class="cell-sm-3 cell-xs-5">
              <div class="preffix-xl-70" style="max-width: 274px">
                <h6 class="text-spacing-200 text-uppercase font-base">Derniers inscrits</h6>

                <div class="divider-modern"></div>
                <ul class="list list-md">
                  <% Profile.where(statut: 'yes').order("created_at DESC").first(3).each do |profile| %>

                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom">
                      <div class="unit-left"><span class="far fa-address-card"></span></div>
                      <div class="unit-body"><a class="link-gray-darker" href="<%=profile_path(profile.id) %>"><%=profile.pseudo.capitalize%> inscrit le <%=profile.created_at.strftime("%d.%m.%Y") %></a></div>
                    </div>
                  </li>
                  <% end %>


                </ul>
              </div>
            </div>
            <div class="cell-sm-3 cell-xs-5">
              <div class="preffix-xl-70" style="max-width: 274px">

                <ul class="list list-md">


                </ul>
              </div>
            </div>
            <div class="cell-sm-4">
              <div class="preffix-xl-70" style="max-width: 433px">


                <ul class="list-inline list-inline-lg">
                  <a href="<%=root_path%>"><button  class="button button-effect-ujarak button-white button-shadow button-circle">Accueil</button></a>
                  <br/>
                  <br/>
                  <a href="<%=profile_path(current_user.profile.id)%>"><button class="button button-effect-ujarak button-primary button-shadow button-circle">Mon profil</button></a>

                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    <div class="snackbars" id="form-output-global"></div>

app/views/pages/info.html.erb
    <div class="text-left page">
      <!-- Page preloader-->
      <div class="page-loader">
        <div>
          <div class="page-loader-body">
            <svg x="0" y="0" width="258" height="258">

              <clippath id="clip-path">

              </clippath>
            </svg>
          </div>
        </div>
      </div>
      <!-- Page Header-->

      <section class="section section-breadcrumb">
        <div class="parallax-container breadcrumb-wrapper" data-parallax-img="https://images.unsplash.com/photo-1476242906366-d8eb64c2f661?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=56490213cac9e45b868b625a4f143eeb&auto=format&fit=crop&w=3108&q=80">
          <div class="parallax-content section-lg context-dark">
            <div class="shell context-dark">
              <h2>Infos</h2>
              <div class="divider"></div>
            </div>
          </div>
        </div>
      </section>
      <!-- Why choose us-->
      <section class="section section-lg bg-white">
        <div class="shell">
          <div class="range range-md-middle range-30">
            <div class="cell-md-6">
              <div class="image-skew" style="max-width: 803px;">
                <div class="image-skew-inner">
                  <div class="image-skew-inner-img"><img src="https://images.unsplash.com/photo-1508239572561-54fae543f43f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=e3e44236f3ee9cf92cdd99168e11be97&auto=format&fit=crop&w=2545&q=80" alt="" width="803" height="458"/>
                  </div>
                </div>
              </div>
            </div>
            <div class="cell-md-4">
              <h2 class="heading-with-aside-divider"><span style="max-width: 380px">Unissons nous.</span><span class="divider"></span></h2>
              <p>Médentraid, c'est avant tout la possibilité de communiquer avec des personnes qui nous ressemblent, mais c'est aussi comprendre les mécanismes d'apparition des risques psychosociaux des professionnels de santé afin de mieux les aborder . Unissons nos réflexions pour une action rapide et efficace .</p>
              <ul class="list-check text-gray-darker">
                <li>Les réseaux sociaux</li>
                <li>Les meetings</li>
                <li>Les colloques</li>
                <li>Les médias</li>
              </ul><a class="button button-lg button-effect-ujarak button-primary" href="<%=root_path%>">Accueil</a>
              <br/>

              <% if  current_user && current_user.profile && current_user.profile.statut == "yes" %>
                      <a class="button button-lg button-effect-ujarak button-primary" href="<%=profile_path(current_user.profile.id)%>" data-caption-animate="fadeInUp" data-caption-delay="450">Mon profil</a>
                    <% elsif current_user && current_user.profile && current_user.profile.statut == "no" %>
                    <a class="button button-lg button-effect-ujarak button-primary" href="<%=root_path%>" data-caption-animate="fadeInUp" data-caption-delay="450"> Profil en attente</a>
                    <% elsif current_user && current_user.profile && current_user.profile.statut == "bloqué" %>
                    <a class="button button-lg button-effect-ujarak button-primary" href="<%=root_path%>" data-caption-animate="fadeInUp" data-caption-delay="450"> Profil bloqué, veuillez contacter l'équipe.</a>

                    <% elsif  current_user && current_user.profile.nil?%>
                        <a class="button button-lg button-effect-ujarak button-primary" href="<%=new_profile_path%>" data-caption-animate="fadeInUp" data-caption-delay="450"> Créer mon profil</a>

                    <% else %>
                    <a class="button button-lg button-effect-ujarak button-primary" href="<%=new_user_session_path %>" data-caption-animate="fadeInUp" data-caption-delay="450">S'inscrire</a>

                    <% end %>
            </div>
          </div>
          <h3>A vos agendas...</h3>
          <!-- Table-->
          <div class="table-custom-responsive">
            <table class="table-custom table-custom-outline">
              <thead>
                <tr>
                  <th>Intitulé</th>
                  <th>Lieu</th>
                  <th>Date</th>
                  <th>Contact</th>

                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>La communication non violente </td>
                  <td>En ligne</td>
                  <td>23 Septembre 2021</td>
                  <td>http://www.asso-sps.fr</td>

                </tr>

              </tbody>
            </table>
          </div>
        </div>
      </section>
      <!-- Page Footer-->


    </div>
    <!-- PANEL-->
    <!-- END PANEL-->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->

app/views/pages/liens.html.erb
    <!-- Page-->
    <div class="text-left page">
      <!-- Page preloader-->
      <div class="page-loader">
        <div>
          <div class="page-loader-body">
            <svg x="0" y="0" width="258" height="258">

              <clippath id="clip-path">

              </clippath>
            </svg>
          </div>
        </div>
      </div>

      <section class="section section-lg bg-white text-left">
        <div class="shell">
          <div class="range range-60 range-xs-center">

            <div class="cell-md-7 cell-lg-5">
              <article class="post">
                <div class="post-header">
                  <div class="post-header-inner">
                    <div class="post-header-inner-img"><a href="http://www.asso-sps.fr/index.html" target="_blank"><img src="http://res.cloudinary.com/dz83jh064/image/upload/v1527364271/logo_sps-2018_w2tufj.jpg" alt="" width="719" height="246"/></a></div>
                  </div>
                </div>
                <div class="post-footer">
                  <h4><a href="http://www.asso-sps.fr/index.html" target="_blank">UNE ASSOCIATION DYNAMIQUE AU SERVICE DES SOIGNANTS EN SOUFFRANCE</a></h4>
                  <div class="post-meta">
                    <p>L’association Soins aux Professionnels en Santé (SPS) a pour origine le rassemblement d’un groupe d’experts souhaitant partager et défendre la santé des professionnels de santé rendus vulnérables.</p>
                  </div>
                </div>
              </article>
            </div>

            <div class="cell-md-7 cell-lg-5">
              <article class="post">
                <div class="post-header">
                  <div class="post-header-inner">
                    <div class="post-header-inner-img"><a href="https://asso-franceburnout.fr/" target="_blank"><img src="http://res.cloudinary.com/dz83jh064/image/upload/v1527365378/nuage_epuisement_200_be5yzt.gif" alt="" width="497" height="80"/></a></div>
                  </div>
                </div>
                <div class="post-footer">
                  <h4><a href="https://asso-franceburnout.fr/" target="_blank">ASSOCIATION FRANCE BURNOUT</a></h4>
                  <div class="post-meta">
                  <p>Notre site internet réunit dans un premier temps toutes les informations permettant aux personnes touchées de mieux comprendre cette maladie d’origine professionnelle, de l’affronter et de se défendre, si nécessaire.
                  </p>
                  </div>
                </div>
              </article>
            </div>

            <div class="cell-md-7 cell-lg-5 wow jackInTheBox">
              <article class="post">
                <div class="post-header">
                  <div class="post-header-inner">
                    <div class="post-header-inner-img"><a href="https://www.association-mots.org/" target="_blank"><img src="http://res.cloudinary.com/dz83jh064/image/upload/v1527365957/Unknown-1_isko2p.png" alt="" width="719" height="246"/></a></div>
                  </div>
                </div>
                <div class="post-footer">
                  <h4><a href="https://www.association-mots.org/" target="_blank">ASSOCIATION MOTS</a></h4>
                  <div class="post-meta">
                    <p>Association mots, au service de la santé des médecins à Toulouse, Marseille, Lille...</p>
                  </div>
                </div>
              </article>
            </div>

            <div class="cell-md-7 cell-lg-5 wow jackInTheBox">
              <article class="post">
                <div class="post-header">
                  <div class="post-header-inner">
                    <div class="post-header-inner-img"><a href="http://asdpro.fr" target="_blank"><img src="http://res.cloudinary.com/dz83jh064/image/upload/v1527366692/cropped-asd_graoq4.png" alt="" width="800" height="280"/></a></div>
                  </div>
                </div>
                <div class="post-footer">
                  <h4><a href="http://asdpro.fr" target="_blank">ASD-Pro</a></h4>
                  <div class="post-meta">
                    <p>Association d'aide aux victimes et aux organisations, confrontées aux suicides et dépressions professionnels.</p>
                  </div>
                </div>
              </article>
            </div>

          </div>

        </div>
      </section>
      <!-- Page Footer-->
      <section class="section section-sm section-full-width bg-gray-bright context-dark">
        <div class="shell">
          <div class="range range-40">
            <div class="cell-lg-3 cell-sm-5">
              <div style="max-width: 274px">
                <h6 class="text-spacing-200 text-uppercase font-base">Infos Contacts</h6>
                <div class="divider-default"></div>
                <ul class="list list-lg">
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom unit-middle">
                      <div class="unit-left"><span class="far fa-address-card"></span></div>
                      <div class="unit-body">Médentraid</div>
                    </div>
                  </li>
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal unit-custom unit-middle">
                      <div class="unit-left"><span class="fas fa-at"></span></div>
                      <div class="unit-body" style="position: relative; top: -1px">infos@medentraid.fr</div>
                    </div>
                  </li>
                  <li>
                    <div class="unit unit-spacing-xs unit-horizontal">
                      <div class="unit-left"><span class="fas fa-home"></span></div>
                      <div class="unit-body" style="position: relative; top: -4px;">Hardelot</div>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
            <div class="cell-lg-3 cell-sm-5">
              <div style="max-width: 283px">
                <h6 class="text-spacing-200 text-uppercase font-base"></h6>
                <br/>
                <div class="divider-default"></div>
                <ul class="list list-lg">


                  <% if current_user &&  current_user.profile &&  current_user.profile.statut == "yes" %>
                  <li>
                    <%= link_to 'Mon profil', profile_path(current_user.profile.id), class:"button button-effect-ujarak button-primary button-block"%>

                  </li>
                  <% elsif current_user &&  current_user.profile &&  current_user.profile.statut == "no" %>
                  <li>
                    <i>Profil en cours de validation</i>
                  </li>

                  <% elsif current_user &&  current_user.profile &&  current_user.profile.statut == "bloqué" %>
                  <li>
                    <i>Votre compte est bloqué, veuillez contacter l'équipe</i>
                  </li>
                  <%elsif current_user &&  current_user.profile.nil? %>
                  <li>
                    <%= link_to "Créer mon profil", new_profile_path, class:"button button-effect-ujarak button-primary button-block"%>
                  </li>
                  <% else %>
                  <li>
                    <%= link_to "S'inscrire", new_user_session_path, class:"button button-effect-ujarak button-primary button-block"%>
                  </li>
                    <% end %>
                </ul>
              </div>
            </div>
            <div class="cell-lg-4">
              <div>
                <h6 class="text-spacing-200 text-uppercase font-base">Une question ? Contactez nous !</h6>
                <p>Vos messages seront supprimés automatiquement après lecture .</p>
                <div class="divider-default"></div>
                <% @contact = Contact.new %>
                <%= simple_form_for [@contact] do |f| %>
                <form class="rd-mailform rd-mailform-mini" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php">
                  <div class="rd-mailform-mini-left">
                    <div class="form-wrap form-wrap-validation">

                      <%= f.input :content , id:"forms-message-footer",label: false, type:"text", name:"Votre message", required: true, class: "form-input", placeholder:"Votre message"%>

                    </div>
                  </div>
                  <div class="rd-mailform-mini-right">
                    <div class="form-wrap form-wrap-validation">

                      <%= f.input :email , id:"forms-email-footer",label: false, type:"string", name:"Votre email", required: true, placeholder:"Votre email", class:"form-input"%>

                    </div>
                    <div class="form-button">
                      <button class="button button-effect-ujarak button-primary button-block button-square" type="submit">envoyer</button>
                    </div>
                  </div>
                </form>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </section>


    </div>
    <!-- PANEL-->
    <!-- END PANEL-->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>

app/views/pages/pourquoi.html.erb
    <!-- Page-->
    <div class="text-left page">
      <!-- Page preloader-->



      <div class="page-loader">
        <div>
          <div class="page-loader-body">
            <svg x="0" y="0" width="258" height="258">

              <clippath id="clip-path">

              </clippath>
            </svg>
          </div>
        </div>
      </div>


      <section class="section section-lg bg-white text-left">
        <div class="shell">
          <div class="range range-40">
            <div class="cell-md-6 cell-lg-7">
              <div class="object">
                <div class="object-left">
                  <div class="image-skew">
                    <div class="image-skew-inner">
                      <div class="image-skew-inner-img"><img src="https://res.cloudinary.com/dz83jh064/image/upload/v1607362052/122387781_10223631771002960_3351462271136532029_n_whdiwm.jpg" alt="" width="300" height="200"/>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="object-right">
                  <h2>Il ne faut plus culpabiliser...</h2>
                  <p>C'est dur de se lever le matin encore plus fatigué qu'au coucher.</p>
                  <p>Et ces angoisses permanentes qui vous bouffent la vie, vous deshumanisent et vous privent de ce qui vous est le plus cher à vos yeux. Le pire, c'est que vous vous sentez obligé d'en faire plus au travail, une force inconnue sans autre alternative . Jusqu'au jour où vous ne savez plus vous lever .  </p>
                </div>
              </div>
              <div class="block-text-width-divider">
                <div class="block-text-width-divider-content">
                  <p>Tout ceci je l'ai vécu. Et dans ces moments, si votre entourage ne comprend pas ou si celui ci n'existe pas, il est très difficile de remonter la pente.  </p>
                  <p>Et là commence le parcours du combattant. Gérer les urgences (fermeture du cabinet, assurances, trouver un remplaçant, gérér la vie familiale) devient impossible, et la culpabilité vous gagne peu à peu, car vous vous sentez responsable de la situation. En France il est encore compliqué d'être professionnel soignant souffrant, voire impossible quand on est en libéral.</p>
                  <div class="quote-demo">
                    <h4 class="quote-demo-title">“Ce qui m'a beaucoup aidé, c'est pouvoir échanger avec des personnes qui me ressemblent.“</h4>
                  </div>
                  <p class="text-spacing-0">Partant de ce constat, il me semblait évident grâce à mes compétences en développement web de créer une plateforme web d'entraide permettant à mes consoeurs et confrères professionnels de santé souffrants de pouvoir communiquer en toute quiétude avec des personnes qui leur ressemblent, le but étant de recouvrer une certaine fierté, de se sentir compris et de pouvoir à nouveau se projeter dans l'avenir. Le site sera amélioré au fur et à mesure du temps grâce à vous et vos bonnes idées que vous pourrez nous soumettre .</p>
                  <div class="single-post-meta">
                    <div class="single-post-meta-item">

                    </div>
                    <div class="single-post-meta-item">

                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="cell-md-4 cell-lg-3">
              <div class="blog-aside">
                <div class="range range-40 range-lg-60">
                  <div class="cell-md-10 blog-aside-item">
                    <div class="rd-navbar-search">

                    </div>
                  </div>
                  <div class="cell-md-10 blog-aside-item">
                    <div class="blog-aside-item-inner">
                      <div class="post-minimal-wrap"><a class="post-minimal" href="#">
                          <div class="unit unit-spacing-xs unit-horizontal">

                            <div class="unit-body">
                            <%= link_to 'Accueil', root_path, class:"button button-effect-ujarak button-primary button-block"%>
                            </div>
                          </div></a><a class="post-minimal" href="#">
                          <div class="unit unit-spacing-xs unit-horizontal">

                            <div class="unit-body">
                              <% if current_user && current_user.profile && current_user.profile.statut == "yes" %>
                              <%= link_to 'Mon profil', profile_path(current_user.profile.id), class:"button button-effect-ujarak button-primary button-block"%>
                              <% elsif current_user && current_user.profile && current_user.profile.statut == "no" %>
                              <%= link_to 'Profil en attente', root_path, class:"button button-effect-ujarak button-primary button-block"%>
                              <% elsif current_user && current_user.profile && current_user.profile.statut == "bloqué"%>
                              <%= link_to 'Profil bloqué', root_path, class:"button button-effect-ujarak button-primary button-block"%>
                              <% elsif current_user && current_user.profile.nil?%>
                              <%= link_to 'Créer mon profil', new_profile_path, class:"button button-effect-ujarak button-primary button-block"%>
                              <% else %>
                              <%= link_to "S'inscrire", new_user_session_path, class:"button button-effect-ujarak button-primary button-block"%>
                              <% end %>
                            </div>
                          </div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- Page Footer-->


    </div>
    <!-- PANEL-->
    <!-- END PANEL-->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>

app/views/pages/test.html.erb
<% @users = User.all%>
<% @users.each do |user|%>

  <p># <%=user.id%>  Email= <%=user.email%> </p>
  <% if user.profile %>
  <p><%=user.profile.id%></p>
  <p><%=user.profile.pseudo%></p>

  <% end %>
<% end %>